[tool.poetry]
name = "dbgear-import"
version = "0.22.0"
description = "Schema and data import functionality for DBGear"
authors = ["tamuto <tamuto@infodb.jp>"]
readme = "README.md"
homepage = "https://github.com/tamuto/dbgear"
repository = "https://github.com/tamuto/dbgear"

packages = [
    { include = "dbgear_import", from = "." }
]

[tool.poetry.scripts]
dbgear-import = "dbgear_import.main:execute"

[tool.poetry.dependencies]
python = "^3.12"
dbgear = "^0.22.0"
# Schema import dependencies
# Data import dependencies (for future Excel support)
openpyxl = { version = "^3.1.2", optional = true }
pandas = { version = "^2.0.0", optional = true }
chardet = { version = "^5.0.0", optional = true }

[tool.poetry.extras]
excel = ["openpyxl", "pandas"]
csv = ["pandas", "chardet"]
all = ["openpyxl", "pandas", "chardet"]

[tool.poetry.group.dev.dependencies]
flake8 = "^3.9.2"
taskipy = "^1.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test = "poetry run python -m unittest discover tests/ -v"
test-fast = "poetry run python -m unittest discover tests/ -k 'not slow'"
lint = "poetry run flake8 dbgear_import/ tests/"
clean = "rm -rf dist/ build/ *.egg-info/"
serve = "poetry run dbgear-import"