parser: '@typescript-eslint/parser'
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
settings:
  react:
    version: detect