/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemasSchemaIdTablesTableIdEditRouteImport } from './routes/schemas/$schemaId/tables/$tableId/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasSchemaIdTablesTableIdEditRoute =
  SchemasSchemaIdTablesTableIdEditRouteImport.update({
    id: '/schemas/$schemaId/tables/$tableId/edit',
    path: '/schemas/$schemaId/tables/$tableId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/schemas/$schemaId/tables/$tableId/edit': typeof SchemasSchemaIdTablesTableIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/schemas/$schemaId/tables/$tableId/edit': typeof SchemasSchemaIdTablesTableIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/schemas/$schemaId/tables/$tableId/edit': typeof SchemasSchemaIdTablesTableIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/schemas/$schemaId/tables/$tableId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/schemas/$schemaId/tables/$tableId/edit'
  id: '__root__' | '/' | '/about' | '/schemas/$schemaId/tables/$tableId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SchemasSchemaIdTablesTableIdEditRoute: typeof SchemasSchemaIdTablesTableIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$schemaId/tables/$tableId/edit': {
      id: '/schemas/$schemaId/tables/$tableId/edit'
      path: '/schemas/$schemaId/tables/$tableId/edit'
      fullPath: '/schemas/$schemaId/tables/$tableId/edit'
      preLoaderRoute: typeof SchemasSchemaIdTablesTableIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SchemasSchemaIdTablesTableIdEditRoute: SchemasSchemaIdTablesTableIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
