[tool.poetry]
name = "dbgear-web"
version = "0.14.3"
description = "Web interface for dbgear database management tools"
authors = ["tamuto <tamuto@infodb.jp>"]
readme = "README.md"
homepage = "https://github.com/tamuto/dbgear"
repository = "https://github.com/tamuto/dbgear"

packages = [
    { include = "dbgear_web", from = "." }
]

[tool.poetry.scripts]
dbgear-web = "dbgear_web.main:execute"

[tool.poetry.dependencies]
python = "^3.12"
dbgear = "^0.14.3"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"