[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dbgear-mcp"
version = "0.1.0"
description = "DBGear MCP (Model Context Protocol) Server"
authors = ["DBGear Team"]
readme = "README.md"
license = "MIT"
packages = [{include = "dbgear_mcp"}]

[tool.poetry.dependencies]
python = "^3.12"
dbgear = {path = "../dbgear", develop = true}
fastmcp = "^2.9.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"

[tool.poetry.scripts]
dbgear-mcp = "dbgear_mcp.main:main"

[tool.taskipy.tasks]
test = "python -m unittest discover tests"
test-fast = "python -m unittest discover tests"
lint = "flake8 dbgear_mcp tests"
clean = "rm -rf dist/ build/ *.egg-info/"
serve = "python -m dbgear_mcp.main"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "dist", "build"]
